### ISSUE TITLE
Update to Evm 0.7 and new travis infrastructure

### ISSUE THREAD

**Issue by AdrieanKhisbe** [AdrieanKhisbe/cask-package-toolset.el#3]
The travis config need to be updated, both in template and as build conf.

For this need to update the script of travis setup. (which should be imported in that repo)

``` yaml
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
```

**Comment by AdrieanKhisbe** [comment]
@rejeep, would you mind fork the project, add your _Setup Evm and Cask on Travis_ script in `bin/travis.sh`, and do a Merge request?

(so that the `.travis.yml` could reference a script behing in that repositery.)
(I prefer you do this, because you are the father of the script, and cask (among other things :))

**Comment by rejeep** [comment]
I'm not really sure what you want me to do here? All there is to it to run EVM on Travis is to add this file (example from f.el): https://github.com/rejeep/f.el/blob/master/.travis.yml

The neat thing is that you can use the same file for all projects. All my projects use this file.

**Comment by AdrieanKhisbe** [comment]
Sorry I guess that I was unclear :/. 

In fact it's https://gist.githubusercontent.com/rejeep/ebcd57c3af83b049833b/raw functionality I would like to bring into the repo as a `setup-evm-on-travis` script.

**Comment by rejeep** [comment]
Yes, but the f.el travis config does that. You should be able to just copy that in be done with it.

(sorry about the late reply, just had a kid... :smile:)

**Comment by AdrieanKhisbe** [comment]
:tada: _CONGRATS @rejeep :D_
(I know it does, but I prefered the commit come from you :)
But you have other things to care about :baby_bottle:  :D)

**Comment by rejeep** [comment]
Right now I'm on a train so I don't have much to do. Is this what you are after? https://github.com/AdrieanKhisbe/cask-package-toolset.el/pull/7

**Comment by AdrieanKhisbe** [comment]
yep, that was the frst part. for the second I had already answered on the PR :)

**Comment by AdrieanKhisbe** [comment]
Now complete since 0.7 :)
 https://github.com/AdrieanKhisbe/cask-package-toolset.el/releases/tag/v0.7.0
