### ISSUE TITLE
not require repo

### ISSUE THREAD

**Issue by dpsutton** [AdrieanKhisbe/cask-package-toolset.el#4]
I'm using cask and your fantastic package to make unit tests. These are for just personal learning, coding exercises, things like that. In particular, this is to make the set of all permutations of a string, just for exercising. Unfortunately, cpt is erroring saying "We could not retrieve project-name from github repo..." and not building the rest. It would be nice if not putting this on github would not break everything.

**Comment by AdrieanKhisbe** [comment]
Can you post me the stack trace? :)

**Comment by AdrieanKhisbe** [comment]
what you could do it specify a fake github repo with the `-g` option flag.
Github repo is only necessary to build the `badges` and `melpa-recipe` 

confirm me that this work.

**Comment by AdrieanKhisbe** [comment]
Hey @dpsutton, did it work?

**Comment by dpsutton** [comment]
i'm sorry. I did that over thanksgiving break and got busy with work again. I'm at work right now but I'll crank up a new cask project with it and check it tonight. thanks for following up and sorry about dropping the ball

**Comment by AdrieanKhisbe** [comment]
no hurry :)

**Comment by AdrieanKhisbe** [comment]
Hello @dpsutton, did you had time to have a look? :)

**Comment by AdrieanKhisbe** [comment]
> $ touch @dpsutton  ; #     :)

**Comment by dpsutton** [comment]
ah sorry. I've just tried again and running into the same scenario
![image](https://cloud.githubusercontent.com/assets/6377293/11915700/d8e9cd32-a678-11e5-8e58-f3fa06102a79.png)

I'm unsure of where to pass the -g option

**Comment by dpsutton** [comment]
![image](https://cloud.githubusercontent.com/assets/6377293/11915712/570e591c-a679-11e5-968b-31b867329d3a.png)

I'll explain the use case that I was trying to do. I wnated to learn emacs lisp and the unit testing that went along with it. So I was using your tools but did not want to use a github repository. It would be nice if there was an easy way to suppress the otherwise nice behavior of looking up badges, etc.

**Comment by dpsutton** [comment]
I apologize about the delay in getting back to you. I just got setup on a new fedora workstation, ditching my macbook and had to get cask and your tools up and running.

**Comment by AdrieanKhisbe** [comment]
No problem @dpsutton  :)

will change the way to retrieve repo name, infering it from `Cask` orfiles or specifying with an option/arg

Waiting for that, here is how ou could do with te `-g` option.
`-g` wait for some _UserName/RepoName_ argument

You should try then `cask exec package-toolset -g fake-user/you-package-name`

confirm me it works :)

**Comment by AdrieanKhisbe** [comment]
added a mention in README: https://github.com/AdrieanKhisbe/cask-package-toolset.el/commit/22f0c0bbc89d68004af5c6fcb5a6bda2591ed187

**Comment by dpsutton** [comment]
thanks so much. that seemed to have worked. I guess its looking for that slash in its validation regex.

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

indeed, it was spliting on `name/repo` :).
I let you close the issue if you consider it done.
