### ISSUE TITLE
Facilitate the creation of a new project

### ISSUE THREAD

**Issue by DamienCassou** [AdrieanKhisbe/cask-package-toolset.el#5]
Use case: I want to create a new project. I want the tool to guide me step by step, starting from nothing.

This is what is achieved by https://github.com/chrisbarrett/skeletor.el. But skeletor is disconnected from cask-package-toolset.

**Comment by AdrieanKhisbe** [comment]
Thanks @DamienCassou! :)
very intersting !!
(I wont :star2: it so far, don't want to break the :four: :two:  :star:  ^^

gonna have a deeper look in the week to see how I can integrate it :)

**Comment by AdrieanKhisbe** [comment]
@DamienCassou.
Do you think I should update https://github.com/chrisbarrett/skeletor.el/tree/master/project-skeletons/elisp-package, or create a `elisp-package-with-ci` ?

And by guiding step by step. You mean `cpt` ou `skeletor`?

**Comment by DamienCassou** [comment]
@AdrieanKhisbe I don't see any reason to create something more than `elisp-package`. Please improve this one.

If you improve skeletor, you don't have anything more to do.

**Comment by AdrieanKhisbe** [comment]
I do agree :)
That will promote proper testing :)

**Comment by AdrieanKhisbe** [comment]
PR merge, I close the issue.
Thanks @DamienCassou for this feature request :)
