### ISSUE TITLE
Cask exec: Error: failed to execute package-toolset

### ISSUE THREAD

**Issue by accidentalrebel** [AdrieanKhisbe/cask-package-toolset.el#8]
So I followed the steps to setup Cask and Cask Package Toolset. I'm on the "Usage" part and tried to run *cask exec package-toolset help". An error appears as seen below:

```
cask exec: error: Failed to execute package-toolset install: [Errno 2] No such file or directory
Did you run cask install?
```

I actually have already run cask install previously. When I try to run it again, it shows this:

```
gnutls.c: [1] (Emacs) GnuTLS library not found
Select coding system (default utf-8): 
```

After pressing enter on the last line, nothing happens. Not sure if the problem is with that missing GnuTLS library or the fact that I am using Windows. 

Any help would be appreciated.

Thanks!

**Comment by AdrieanKhisbe** [comment]
Sorry for the late answer @accidentalrebel .
What is the emacs version you are using? 

Since you are using windows it might be related to the following issue I found on emacsoverflow:
http://emacs.stackexchange.com/questions/27202/how-do-i-install-gnutls-for-emacs-25-1-on-windows

**Comment by accidentalrebel** [comment]
Hi @AdrieanKhisbe I actually need to revisit this by setting up Cask again. Will let you know once I do. :) 

Also it's been awhile and I've already upgraded to Emacs 25.1 from Emacs 24 so not sure if this would still be a problem. We will know soon.

Thanks!

**Comment by AdrieanKhisbe** [comment]
Okey dokey. Waiting for your input :)

**Comment by accidentalrebel** [comment]
Good day! 

I reinstalled Cask on my current version of Emacs (GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-18) as well as the latest version of cask-package-toolset. I also did the solution in the stackexchange link that you shared. Sadly the problem still remains.

The line  `cask exec bin/package-toolset help`

Still generates the following error:
```
cask exec: error: Failed to execute bin/package-toolset help: [Errno 2] No such file or directory
Did you run cask install?
```
I verified my cask paths and the correct path for package-toolset's bin is there. `cask exec-path` returns the correct paths including `[elisp package path]/.cask/25.1/elpa/cask-package-toolset-20160102.137/bin;`. In spite of this `cask exec` could not find the file.  

To make sure that there was no problem with `cask exec` I verified that it works by using `cask exec notepad.exe`. It seems that it works properly as long as "notepad.exe" is searchable in the $PATH environment variable. 

After some digging I found [this comment](https://github.com/cask/cask/pull/239#issuecomment-55113808) from an issue in the Cask github page:

> The issues with ert-runner and ecukes are not cask issues, but rather lack of Windows support in them (which at a glance would require either running under cygwin to ensure shebang is processed properly or conversion to powershell/bat/vbs for native Windows support).

Thinking that it might probably be a problem with Windows not being able to run bash scripts I decided to try to do this:
`cask exec $EMACS --script "[elisp package path]/.cask/25.1/elpa/cask-package-toolset-20160102.137/cask-package-toolset.el" --help`

And it returned: `Give us a command. install for instance, or consult usage with help`

Could it be simply a problem with the bash script? I am not well versed in bash scripts but could it be related to the `$(dirname $(dirname` lines inside "bin/package-toolset"?

Hope you can help me with this one. I'm willing to be a tester if you need someone to test on Windows.

Thanks!

**Comment by accidentalrebel** [comment]
This line seems to work
`cask exec $EMACS --script "[elisp package path]/.cask/25.1/elpa/cask-package-toolset-20160102.137/cask-package-toolset.el" -- "status"`

It returns:
```
- Makefile                You should run `package-toolset setup'
- .gitignore              You should run `package-toolset setup'
- .travis.yml             You should run `package-toolset setup'
- Ert Test                You should run `cask exec package-toolset setup-ert'
- Ecukes Features         You should run `cask exec ecukes new'
```

So I guess it is progress :)

**Comment by AdrieanKhisbe** [comment]
Shall I close the issue then?

**Comment by accidentalrebel** [comment]
Yep. I think I'm good.

**Comment by AdrieanKhisbe** [comment]
good :)
